### ISSUE TITLE
たまにrqtの真ん中の画像が出ない理由

### ISSUE THREAD

**Issue by YuOhara** [start-jsk/rtmros_choreonoid#100]
2台PCを使ってる場合は、通信しすぎのようです。
image_rawとcamera_infoのsyncができてないのいけないので、それで出てないんだと思います.
今まではシミュレータの側でsyncしてたのでちゃんと動いてました。

解決策
* fc->ocsの順であげる。おそらく先に作られたnodeが優先されるっぽいので（適当です）、それでうまく行っている
* 通信量を減らす。

**Comment by YuOhara** [comment]
multisense_localのトピックを作るところを（現状必要なかった）をなくすことによって多少風通しがよくなり、多少解決。

**Comment by YoheiKakiuchi** [comment]
画像や点群のfpsを減らすのは役に立つかな？

**Comment by YuOhara** [comment]
現状上のdiffによってプログラムは動いてるのですが、
減らせるなら、減らしてもらった方が良さそうです。

ただ、laserはslamに使ってるので、減らさない方が良さそうです。

**Comment by YuOhara** [comment]
rqtが見えない件ですが、
https://github.com/jsk-ros-pkg/jsk_common/pull/1281
が原因だった回もありました。
通信については、jvrcでちゃんと動くくらいには解決しました。
