### ISSUE TITLE
go-posが帰ってこない

### ISSUE THREAD

**Issue by YuOhara** [start-jsk/rtmros_choreonoid#104]
https://github.com/start-jsk/rtmros_common/issues/839
と関係する話という噂をききましたが、go-posが帰ってこなくなりました。。。

**Comment by garaemon** [comment]
帰ってこない間、hrpsysは動いていますか? joint_statesは出ていますか?

**Comment by garaemon** [comment]
* 次は`:wait-foot-steps`のサービスコールが呼ばれているかを確認、ですね。(たぶん呼ばれている)
* hrpsysの対応するサービスのところにプリント分をいれてみて、どこで止まっているか確認.

**Comment by snozawa** [comment]
```
roscd hrpsys_tools/scripts
python hrpsys_config_tools.py -i --use-unstable-rtc
hcf.waitFootSteps()
# or 
hcf.emergencyStop()
```
でpythonで確認できます。

**Comment by YutaKojio** [comment]
コジオです。
先ほどgo-posが返ってこない問題が再発しました。

少し前に黒岩さんにdebug文を入れてもらった状態でchoreonoidをあげていましたが、logを見る感じでは、debugをはさんだwhileループから抜けていないように思われます。

logとdebugをはさんだ箇所のスクショが以下になります。

![screenshot from 2015-10-07 16 24 39](https://cloud.githubusercontent.com/assets/11713954/10331481/c6ae227c-6d10-11e5-963e-7d73758d92a7.png)

**Comment by eisoku9618** [comment]
go-posからfoot stepを作る部分の収束条件が満たされずに，foot stepを作り続けているのが原因のようです．

positionの方の収束条件：0.1mm
rotationの方の収束条件：0.5度

なところで，以下のようにpositionの方が0.24mmくらいで収束していませんでした．
0.1mmのしきい値を10mmにして試してみています．

In [14]: dp
Out[14]: array([  2.16751000e-18,   1.65349000e-16,   2.47467000e-04])

In [15]: dr
Out[15]: array([ -6.53854000e-05,   2.15807000e-05,  -3.51280000e-16])

In [19]: numpy.sqrt(numpy.dot(dp, dp.transpose())) * 1e3
Out[19]: 0.24746700000000002

In [17]: numpy.sqrt(numpy.dot(dr, dr.transpose()))
Out[17]: 6.8854753980026676e-05


2015-10-07 16:31 GMT+09:00 Yuta Kojio <notifications@github.com>:

**Comment by terasawa** [comment]
ちなみに（歩幅を変えている，go-posの指令を遠くにしすぎていなど）収束していない理由で考えられることはありますか？

今までの現象を見る限り，最初にgo-posが動けばそれ以降はうまく動いていた場合が多かったのですが，
収束しない条件が何かあるとしたら，１回動けばそれ以降は送れるというのはたまたまで
何回かgo-posできていても起こりうる気がしていますが．．．

**Comment by h-kamada** [comment]
* 0.1の部分を10にしてやってみたところ、２回ともgo-posできました。
今から1としてやってみます。

**Comment by YuOhara** [comment]
hrpsys-baseで報告していただいたようなのでcloseします．

* 現状はgo-posが返ってこないところに関しては解決している．
