### ISSUE TITLE
GUIの日本語表示

### ISSUE THREAD

**Issue by snozawa** [start-jsk/rtmros_choreonoid#172]
choreonoid単独で起動すると、GUIが日本語になります。
rtmlaunch hrpsys_choreonoid_tutorials jaxon_red_choreonoid.launchすると、英語になります。
日本語表示にしたいのですが、launchのどこかで設定されてますか？
また、日本語をデフォにするのはいかがでしょうか。

**Comment by YoheiKakiuchi** [comment]
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_tools/launch/hrpsys.launch#L12

ここに引っ張られているように思うので、jaxon_red_choreonoid.launchのhrpsys.launchを呼ぶところで、LANGを与えるといいかと思います。 ```$(env LANG)``` を渡すと、呼んだ環境とおなじになるかな？

**Comment by snozawa** [comment]
hrpsys_toolsのhrpsys.launc, rosbridgeのhrpsys_ros_bridge.launchのLANG=Cを日本語ja_JP.UTF-8セットしてみてますが、かわんないですね。。。

**Comment by snozawa** [comment]
choreonoid.launchの一ヶ所だけでいけました。

**Comment by snozawa** [comment]
closed via https://github.com/start-jsk/rtmros_choreonoid/pull/174
