### ISSUE TITLE
歩くと左に傾く

### ISSUE THREAD

**Issue by YutaKojio** [start-jsk/rtmros_choreonoid#190]
https://github.com/s-nakaoka/choreonoid/issues/111 の解決により，
今までは両足立ちでstを入れると右に傾いていたのが，傾かなくなりました．
しかし，この状態でgoposすると左に傾き気味になり，たまに転けるようになりました．

https://github.com/start-jsk/rtmros_choreonoid/blob/master/jvrc_models/JAXON_JVRC/JAXON_JVRCmain_hrpsys_bush.wrl#L240-L245 を`rotation 1 0 0 0`にして，
あえて右に傾かせると今まで通りにきれいに歩けます．

**Comment by snozawa** [comment]
どこかに
s-nakaoka/choreonoid#111
対策のhotfixコードが残ってたりしないかな？

**Comment by YoheiKakiuchi** [comment]
https://drive.google.com/open?id=0B5IZpi1aPoszNU9VT09sN1ZoN2M

僕の手元の最新と思う環境です。(ソースの修正なし、wrlの修正も入っていない）
(choreonoidはdebで、20160629のバージョン)

止まっている時の JAXON_RED/WAISTのRollは0.0degで、このときkf.rtcの出力は
wrlで傾けている分だけ、傾いていました。

歩いているときは、+0.4 ~ -0.6 deg ぐらいRollがふらつきますが、問題ない範囲かと思います。
これとは明らかに違いますか？

**Comment by YutaKojio** [comment]
歩けている人と歩けない人がいる理由はわかりました．
st-algorithmがEEFMだと歩けてEEFMQPだとおかしくなります．
https://drive.google.com/open?id=0B9Cu2eewhmiwRnQ3SHJMT256b0E

hrpsysをビルドするときにDUSE_QPOASES=ONにしていいない人はEEFMなので歩けているようです．
EEFMQPのバグだとしても右に傾けるとなぜうまくいくのかはわからないです．．．

**Comment by snozawa** [comment]
あれこれ実機でも一時期おきてませんでしたっけ？
２月くらいに。
それで、取り急ぎでEEFMQPCOPにすると動くようになってた気がします。

**Comment by YutaKojio** [comment]
EEFMQPCOPにすると歩けました．
choreonoidでimuが傾いていたバージョンでずっと歩けていたのはたまたまで，
最近転けるようになったのはchoreonoidの問題ではなく，hrpsys側の問題ということでよさそうです．

**Comment by snozawa** [comment]
そうするとJAXONで実機もsimulatorもEEFMQPだと歩けないような状況のきがしますね。
取り急ぎ問題ないのであれば、EEFMQPCOPがいいような気がします。
（本当は調べておきたいですが）

**Comment by YoheiKakiuchi** [comment]
> hrpsysをビルドするときにDUSE_QPOASES=ONにしていいない人はEEFMなので歩けているようです．

これは、hrpsysを(indigo_parentなどのソースで)ただcatkin buildするだけではなくて、
オプションをつけてビルドする必要があるということでしょうか？
それで、体内はそうなっていますか？

ロボットがそこそこ可動実績あるなら、ロボットに入っているdiffはとりあえずコミット
してもらってロボット内にdiffがある状況をなくしていきましょう。

**Comment by snozawa** [comment]
>  それで、体内はそうなっていますか？

手元でも体内でもそうしています。
ただ、このQPOASESが必要なSTのモード（EEFMQP）自体最近あまり使ってないと思います。
このSTモードを変えるdiffは、体内に残ってる気がしてきたので、ここ最近動いてきてることを
考えるとコミットでよいかもしれません。

**Comment by YoheiKakiuchi** [comment]
https://github.com/start-jsk/rtmros_tutorials/pull/489
ここで変更しようとしているかと思います。

> hrpsysをビルドするときにDUSE_QPOASES=ONにしていいない人はEEFMなので

EEFMQPCOP は 同じく DUSE_QPOASES=ON が必要でしょうか？

**Comment by YutaKojio** [comment]
> EEFMQPCOP は 同じく DUSE_QPOASES=ON が必要でしょうか？

いらないです．

**Comment by YutaKojio** [comment]
https://github.com/start-jsk/rtmros_tutorials/pull/489 でとりあえず歩くようにはなりました．
