### ISSUE TITLE
シミュレーション中にオブジェクトを追加したい

### ISSUE THREAD

**Issue by ishiguroJSK** [start-jsk/rtmros_choreonoid#321]
ros_service_server.pyが含まれているcnoidプロジェクトで

```
>>> addObject("aaa", "/usr/local/choreonoid/share/choreonoid-1.6/model/misc/box1.body")
'(:success)'
```
としても非干渉なモデルが描画されるだけになる
今回は踏み台のようなstaticなモデルですが，ボールのようなオブジェクトだとアイテムツリー内でボール以下にAISTSimulatorがぶら下がる気がしますが，だれかこれでうまく行った実績ありますか？

![Screenshot from 2020-03-10 13%3a28%3a14](https://user-images.githubusercontent.com/18138979/76279787-4563a080-62d3-11ea-9e80-7c34d87f8062.png)

**Comment by YoheiKakiuchi** [comment]
前にできると言ったんですが、ダイナミックにできていなかった気がしてきました。
一回シミュレーションを止めて、再度実行すると認識される気がします。
(スタート・ポーズはjskのhrpsysを使うパターンだと上手く行っていないきがする。)

動的物体になるか、静的物体になるかは、モデルファイルの書き方にも依存しているかもしれない。
wrlだと、worldとのfreeジョイントがないと動的物体にならないように動いていたように思う。
.bodyはどうだか分からない。

**Comment by ishiguroJSK** [comment]
なるほど，ありがとうございます．
階段の高さのパラチュンが出来ればいいので，yamlに書いて起動時に読ませる方針で行こうと思います．
