### ISSUE TITLE
jaxonがヘタってしまう．

### ISSUE THREAD

**Issue by otsubo** [start-jsk/rtmros_choreonoid#94]
choreonoid $(rospack find hrpsys_ros_bridge_jvrc)/config/JVRCR4.cnoid
を実行して,シミュレーションをスタートすると,ジャクソンがヘタってしまいます.
以下ログです.
otsubo@axis:~$ choreonoid $(rospack find hrpsys_ros_bridge_jvrc)/config/JVRCR4.cnoid
Loading body customizer "/usr/lib/choreonoid-1.5/customizer/HoseCustomizer.so" for hose
Loading body customizer "/usr/lib/choreonoid-1.5/customizer/JAXONCustomizer.so" for JAXON_JVRC
Loading body customizer "/usr/lib/choreonoid-1.5/customizer/CabinetBoxCustomizer.so" for CABINETBOX
create customizer : JAXON_JVRC
PDcontroller0: onInitialize() 
create customizer : JAXON_JVRC
cloneMap.setNonNodeCloning(false);
cloneMap.setNonNodeCloning(false);
cloneMap.setNonNodeCloning(false);
cloneMap.setNonNodeCloning(false);
cloneMap.setNonNodeCloning(false);
cloneMap.setNonNodeCloning(false);
cloneMap.setNonNodeCloning(false);
PDcontroller0: on Activated 
[PDcontroller0] Gain file [] not opened

![screenshot from 2015-10-01 19 25 04](https://cloud.githubusercontent.com/assets/6928359/10218510/28d033bc-6872-11e5-9885-fe91b1a80ab7.png)

hrpsys_ros_bridge_jvrc/models以下にはJAXON_JVRC.PDgains.datがちゃんとあります.
どう対処すればよいでしょうか．

**Comment by YoheiKakiuchi** [comment]
> git pull した後、
roscd jvrc_models; bash setup_jvrc.sh
してください

これやってるかな？

> /home/leus で
choreonoid $(rospack find hrpsys_ros_bridge_jvrc)/config/JVRCO1.cnoid

それと、ホームディレクトリでchoreonoidを走らせる必要があります。

あと、homeに rtc.conf.choreonoid はありますか？

**Comment by otsubo** [comment]
> あと、homeに rtc.conf.choreonoid はありますか？
これがありませんでした.
このファイルはどこで生成されるのでしょうか.

**Comment by YoheiKakiuchi** [comment]
https://github.com/start-jsk/rtmros_choreonoid/pull/95
修正しました。
本番に向けて、いくつかでユーザー名固定になってしまっています。

setup_jvrc.sh をもう一度してみてください。

あと、
```$(rospack find hrpsys_ros_bridge_jvrc)/config/JVRCO1.cnoid```
cnoidファイルにもleusが入ってしまっているので、ここを自分のユーザー名にしてください。

**Comment by otsubo** [comment]
なぜか
```bash
bash setup_jvrc.sh
```
すると,許可がないと言われたので,rtmros_choreonoidごと入れなおして,buildしたら正常に動作しました.
